Repository iver-wharf/wharf-provider-github, pull requests merged in 2021-07, with the labels that each got.

#17 Updated golang & alpine Docker images
  CHANGELOG.md
  Dockerfile
Labels: enhancement

#18 Release v2.0.0
  CHANGELOG.md
Labels: release

#21 Fix date in v2.0.0
  CHANGELOG.md
Labels: enhancement

#23 Added PR templates
  .github/.remarkrc
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  package.json
Labels: documentation

#22 Added missing go.mod item
  go.mod
Labels: bug

#20 Added wharf-core logging
  CHANGELOG.md
  github.go
  go.mod
  go.sum
  main.go
Labels: enhancement

#19 Added config and backward compatability
  CHANGELOG.md
  README.md
  config.go
  config_example_test.go
  github.go
  go.mod
  go.sum
  internal/httputils/httpclient.go
  main.go
Labels: enhancement

#16 Reworked error output to send IETF RFC-7807 compatible problem responses
  CHANGELOG.md
  README.md
  github.go
  go.sum
Labels: enhancement
